# Generated by Django 4.1.3 on 2022-11-27 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filtered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefect_name', models.CharField(max_length=50)),
                ('vote_count', models.IntegerField(default=0)),
                ('prefect_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('poll_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.position')),
                ('select_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.filtered')),
            ],
        ),
    ]
