# Generated by Django 4.1.3 on 2022-11-27 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='prefect_name',
            new_name='voter_name',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='prefect_photo',
            new_name='voter_photo',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='poll_position',
            new_name='voter_position',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='select_filter',
        ),
        migrations.AddField(
            model_name='position',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Filtered',
        ),
    ]
