# Generated by Django 4.1.3 on 2022-11-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_poll_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='username',
        ),
    ]
