# Generated by Django 4.1.3 on 2022-11-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_alter_poll_voter_position_delete_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_position', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='poll',
            name='voter_name',
            field=models.CharField(max_length=200),
        ),
    ]
