# Generated by Django 4.1.3 on 2022-12-05 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0005_alter_poll_voter_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_course', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_range', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompleteRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default=0, max_length=10)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('relation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.studentrange')),
                ('your_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.studentcourse')),
            ],
        ),
    ]
