# Generated by Django 4.1.3 on 2022-12-11 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0008_poll_have_vote_delete_havevote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='have_vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
