# Generated by Django 4.1.3 on 2022-12-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_completeregistration_can_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeregistration',
            name='can_vote',
        ),
    ]
