# Generated by Django 4.1.3 on 2022-12-15 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0013_remove_completeregistration_can_vote_canvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canvote',
            old_name='relation',
            new_name='relation1',
        ),
    ]
