# Generated by Django 4.1.3 on 2022-12-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0014_rename_relation_canvote_relation1'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeregistration',
            name='can_vote',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='CanVote',
        ),
    ]
