# Generated by Django 4.1.3 on 2022-12-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0015_completeregistration_can_vote_delete_canvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSitting1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_vote', models.BooleanField(default=False)),
                ('registration_complete', models.BooleanField(default=False)),
                ('show_results', models.BooleanField(default=False)),
            ],
        ),
    ]
