# Generated by Django 4.1.3 on 2022-12-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0017_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='voter_name',
            new_name='person_name',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='voter_photo',
            new_name='person_photo',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='voter_position',
            new_name='person_position',
        ),
    ]
