# Generated by Django 4.1.3 on 2022-12-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0018_rename_voter_name_poll_person_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='voter_position',
            new_name='person_position',
        ),
    ]
