# Generated by Django 4.1.3 on 2022-12-18 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0019_rename_voter_position_position_person_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='person_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poll.studentcourse'),
            preserve_default=False,
        ),
    ]
