# Generated by Django 4.1.3 on 2022-12-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0020_poll_person_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsitting1',
            name='be_inform',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
